login/urls.py
from django.conf.urls import url
from . import views

app_name = "login"

urlpatterns = [

    ##url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^$', views.UserLoginView.as_view(), name='login'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    
]

pymeet/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from login.views import LogoutView, HomeView

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^', include('login.urls')),
    url(r'^logout', LogoutView.as_view(), name='logout'),
    url(r'^home/',  HomeView.as_view(), name='home'),
    url(r'^tasks/', include('task.urls')),
]

##if settings.DEBUG:
##	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
##	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.conf.urls import url
from . import views

app_name = "task"

urlpatterns = [

    ##url(r'^$', views.LoginView.as_view(), name='login'),
    url(r'^$', views.TasksView.as_view(), name='tasks'),
    url(r'^(?P<pk>[0-9]+)/$', views.TasksDetailView.as_view(), name='detail_task'),
    url(r'^(?P<tk>[0-9]+)/delete/(?P<pk>[0-9]+)/$', views.TaskDelete.as_view(), name='delete_task'),
    url(r'^(?P<pk>[0-9]+)/add/$', views.AddTask.as_view(), name='add_task'),
    url(r'^add-task-list/$', views.AddTaskList.as_view(), name='add_task_list'),
    
    
    
]

task/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User



class TaskList(models.Model):
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	list_title = models.CharField(max_length=100)

	def get_absolute_url(self):
		return reverse('task:detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.list_title + ' - ' + str(self.owner)


class Task(models.Model):
	task_owner = models.ForeignKey(TaskList, on_delete=models.CASCADE)
	task_name = models.CharField(max_length=250)
	task_desc = models.CharField(max_length=250)
	task_deadline = models.DateTimeField(auto_now_add=True)
	is_done = models.BooleanField(default = False)

	def __str__(self):
		return str(self.task_name)

login/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):

	password = forms.CharField(widget = forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username','email','password']


class UserLoginForm(forms.Form):

	username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
	fields = ['username', 'password']

task/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User


class UserAddTaskForm(forms.ModelForm):

	task_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Add Todo'}))

	class Meta:
		model = Task
		fields = ['task_name']


class UserAddTaskListForm(forms.ModelForm):

	'''users = User.objects.all()
	CHOICES = ()

	if users:
		for user in users:
			CHOICES = CHOICES + ((user, user.username),)

	owner = forms.ChoiceField(choices=CHOICES)'''

	class Meta:
		model = TaskList
		fields = ['list_title']

login/views.py
from django.views import generic
#from .models import Album
#from django.views.generic.edit import CreateView, UpdateView, DeleteView
#from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.views.generic import View
#from .models import Album
from .forms import UserForm, UserLoginForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.views.generic import RedirectView
from django.urls import reverse


from task.models import *
from task.forms import UserAddTaskListForm


class LoginView(generic.ListView):
	model = TaskList
	template_name = "login/login.html"

	def get_queryset(self):
		return None

class HomeView(LoginRequiredMixin, generic.ListView):
	template_name = "login/home.html"
	context_object_name = 'all_tasks_by_user'
	form_class = UserAddTaskListForm

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

class UserFormView(View):
	form_class = UserForm
	template_name = "login/registration_form.html"


	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit = False)

			# cleaned normalized data

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user.set_password(password)
			user.save()

			# returns User object if the credentials are true

			user = authenticate(username=username, password = password)

			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('/')

		return render(request, self.template_name, {'form': form})

class UserLoginView(View):
	form_class = UserLoginForm
	form_class_reg = UserForm
	template_name = "login/registration_form.html"



	# display blank form
	def get(self, request):
		form = self.form_class(None)

		return render(request, self.template_name, {'form': UserForm})

	def post(self, request):
		form  = self.form_class(request.POST)

		if form.is_valid():

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user = authenticate(username=username, password = password)
			
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('/home/')

		return render(request, self.template_name, {'form': UserForm})

class LogoutView(View):

	template_name = "login/logout.html"


	# display blank form
	def get(self, request):
		if self.request.user.is_authenticated:
			logout(self.request)
		return render(request, self.template_name)

task/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import *
from django.urls import reverse_lazy
from pymeet.utils import *
from django.http import HttpResponse
from .forms import *
import datetime
from django.http import HttpResponseRedirect


class TasksView(LoginRequiredMixin, generic.ListView):
	template_name = "login/home.html"
	#context_object_name = 'all_albums'

	def get_queryset(self):
		return None


class TasksDetailView(LoginRequiredMixin, generic.ListView):
	model = Task
	template_name = "tasks/task_detail.html"
	context_object_name = 'task_details'
	form_class = UserAddTaskForm

	#def get_queryset(self, **kwargs):
	#	return Task.objects.filter(task_owner=self.kwargs["pk"])

	def get(self, request, *args, **kwargs):

		return render(request, 'tasks/task_detail.html', 
			{'task_details': Task.objects.filter(task_owner=self.kwargs["pk"]), 'add_form': UserAddTaskForm})
		#return Task.objects.filter(task_owner=self.kwargs["pk"])

	def post(self, request, *args, **kwargs):

		is_done = request.POST.get('is_done')
		tk = request.POST.get('pk')

		try:
			obj = Task.objects.get(pk=tk)
			obj.is_done = check_is_true(is_done)
			obj.save()
		except:
			return HttpResponse(status=500)
		
		return render(request, self.template_name, 
			{'task_details': Task.objects.filter(task_owner=self.kwargs["pk"]), 'add_form': UserAddTaskForm})




class TaskDelete(LoginRequiredMixin, generic.DeleteView):
	model = Task

	def get_success_url(self):
		return reverse_lazy('task:detail_task', kwargs={'pk': self.kwargs["tk"]})

class AddTask(LoginRequiredMixin, generic.ListView):
	model = Task
	form_class = UserAddTaskForm
	template_name = "tasks/task_detail.html"

	def get(self, request):
		return None

	def post(self, request, *args, **kwargs):

		form = self.form_class(request.POST)

		if form.is_valid():

			task = form.save(commit = False)
			next = request.POST.get('next', '/')

			# cleaned normalized data (Date field ex)

			task.task_name = form.cleaned_data['task_name']
			task.task_owner = TaskList.objects.get(pk=self.kwargs["pk"])
			task.desc = ""
			task.save()

			
			return HttpResponseRedirect(next)

class AddTaskList(LoginRequiredMixin, generic.ListView):
	model = TaskList
	form_class = UserAddTaskListForm

	def post(self, request, *args, **kwargs):

		form = self.form_class(request.POST)

		if form.is_valid():

			tasklist = form.save(commit = False)
			tasklist.owner = request.user
			tasklist.save()

			
			return HttpResponseRedirect("/home")

templates/login/404_page.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<style>
.bigjumb{ margin-top: 10%;}
</style>


<div class="container">
    <div class="jumbotron bigjumb">
        <div class="text-center"><i class="fa fa-5x fa-frown-o" style="color:#d9534f;"></i></div>
        <h1 class="text-center">404 Not Found<p> </p><p><small class="text-center"> Oh noes everything broke</small></p></h1>
        <p class="text-center"></p>
    </div>
</div>

<!--
<script>
window.setTimeout(function(){

        // Move to a new location or you can do something else
        window.location.href = "/";

    }, 5000);
</script> -->

templates/login/admin_home.html
{% extends 'login/base.html' %}
<h3>Home</h3>

{% block body %}



<div id="throbber" style="display:none; min-height:120px;"></div>
<div id="noty-holder"></div>
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://cijulenlinea.ucr.ac.cr/dev-users/">
                <img src="http://placehold.it/200x50&text=LOGO" alt="LOGO">
            </a>
        </div>
        <!-- Top Menu Items -->
        <ul class="nav navbar-right top-nav">
                     
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }} <b class="fa fa-angle-down"></b></a>
                <ul class="dropdown-menu">
                    <!--<li><a href="#"><i class="fa fa-fw fa-user"></i> Edit Profile</a></li>-->
                    <!--<li><a href="#"><i class="fa fa-fw fa-cog"></i> Change Password</a></li>-->
                    <!--<li class="divider"></li>-->
                    <li><a href="{% url 'logout' %}"><i class="fa fa-fw fa-power-off"></i> Logout</a></li>
                </ul>
            </li>
        </ul>
        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">
                <li>
                    <a href="#" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-fw fa-search"></i> MENU 1 <i class="fa fa-fw fa-angle-down pull-right"></i></a>
                    <ul id="submenu-1" class="collapse">
                        <li><a href="#"><i class="fa fa-angle-double-right"></i> SUBMENU 1.1</a></li>
                        <li><a href="#"><i class="fa fa-angle-double-right"></i> SUBMENU 1.2</a></li>
                        <li><a href="#"><i class="fa fa-angle-double-right"></i> SUBMENU 1.3</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" data-toggle="collapse" data-target="#submenu-2"><i class="fa fa-fw fa-star"></i>  MENU 2 <i class="fa fa-fw fa-angle-down pull-right"></i></a>
                    <ul id="submenu-2" class="collapse">
                        <li><a href="#"><i class="fa fa-angle-double-right"></i> SUBMENU 2.1</a></li>
                        <li><a href="#"><i class="fa fa-angle-double-right"></i> SUBMENU 2.2</a></li>
                        <li><a href="#"><i class="fa fa-angle-double-right"></i> SUBMENU 2.3</a></li>
                    </ul>
                </li>
                <li>
                    <a href="investigaciones/favoritas"><i class="fa fa-fw fa-user-plus"></i>  MENU 3</a>
                </li>
                <li>
                    <a href="sugerencias"><i class="fa fa-fw fa-paper-plane-o"></i> MENU 4</a>
                </li>
                <li>
                    <a href="faq"><i class="fa fa-fw fa fa-question-circle"></i> MENU 5</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>

    <div id="page-wrapper">
        <div class="container-fluid">
            <!-- Page Heading -->
            <div class="row" id="main" >
                <div class="col-sm-12 col-md-12 well" id="content">
                    <h1>Welcome {{ user.username }}!</h1>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->
</div><!-- /#wrapper -->



  
{% endblock %}


<script>
$(function(){
    $('[data-toggle="tooltip"]').tooltip();
    $(".side-nav .collapse").on("hide.bs.collapse", function() {                   
        $(this).prev().find(".fa").eq(1).removeClass("fa-angle-right").addClass("fa-angle-down");
    });
    $('.side-nav .collapse').on("show.bs.collapse", function() {                        
        $(this).prev().find(".fa").eq(1).removeClass("fa-angle-down").addClass("fa-angle-right");        
    });
})    
    
</script>

templates/login/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Erkanderon{% endblock %}</title>
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy" />
<link rel="stylesheet" type="text/css" href="{%  static 'styles.css'  %}">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
</head>

<body>



{% block body %}

{% endblock %}

</body>

</html>

templates/login/form_template.html
{% for field in form %}
	<div class="form-group regform">
		<div class="col-sm-12">
			<span class="text-danger small"> {{field.errors}}</span>
		</div>
		<label class="control-label col-xs-12">{{field.label_tag}}</label>
		<div class="col-sm-12">{{field}}</div>
	</div>
{% endfor %}


<script>

	$( document ).ready(function() {
	    document.getElementById("id_username").setAttribute("required", "");
	    document.getElementById("id_email").setAttribute("required", "");
	    document.getElementById("id_password").setAttribute("required", "");
	});
</script>

templates/login/home.html
{% extends 'login/base.html' %}
<h3>Home</h3>

{% block body %}

{% include 'login/sidebar.html' %}
<div class="main">
<!-- Content Here -->

	<div class="container">
	    <div class="row">
	        <form action="/tasks/add-task-list/" method="post">
	        	{% csrf_token %}
	        	{{ form }}
	        	<button type="submit">Add List</button>
	        </form>
	    </div>
	</div>
</div>



<!--

<h1>Welcome {{ user.username }}!</h1>

   <a href="{% url 'logout' %}"><i class="fa fa-fw fa-power-off"></i> Logout</a>

{% for announce in all_tasks_by_user %}
<h1>{{announce.owner}}</h1>
    <p>{{announce.list_title}}</p>

{% endfor %}
-->

<script>
function htmlbodyHeightUpdate(){
		var height3 = $( window ).height()
		var height1 = $('.nav').height()+50
		height2 = $('.main').height()
		if(height2 > height3){
			$('html').height(Math.max(height1,height3,height2)+10);
			$('body').height(Math.max(height1,height3,height2)+10);
		}
		else
		{
			$('html').height(Math.max(height1,height3,height2));
			$('body').height(Math.max(height1,height3,height2));
		}
		
	}
	$(document).ready(function () {
		htmlbodyHeightUpdate()
		$( window ).resize(function() {
			htmlbodyHeightUpdate()
		});
		$( window ).scroll(function() {
			height2 = $('.main').height()
  			htmlbodyHeightUpdate()
		});
	});
</script>
  
{% endblock %}

templates/login/login_form.html
{% extends 'login/base.html' %}
{% block title %}Login{% endblock %}
{% block body %}
<div class="container-fluid">
	<div class="row cent">

		<div class="col-xs-12 col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'login/form_template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>

				</div>
			</div>
		</div>

	</div>
</div>



{% endblock %}

templates/login/logout.html
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>


<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<style>
.bigjumb{ margin-top: 10%;}
</style>


<div class="container">
    <div class="jumbotron bigjumb">
        <div class="text-center"><i class="fa fa-5x fa-frown-o" style="color:#d9534f;"></i></div>
        <h1 class="text-center">Logged Out<p> </p><p><small class="text-center"> Oh noes everything broke</small></p></h1>
        <p class="text-center">See You Next Time</p>
    </div>
</div>


<script>
	window.setTimeout(function(){

        // Move to a new location or you can do something else
        window.location.href = "/";

    }, 5000);
</script>

templates/login/registration_form.html
{% extends 'login/base.html' %}
{% block title %}Register{% endblock %}
{% block body %}


<div class="container">
	<div class="row loginform">
		<div class="col-md-4 col-md-offset-4">
			<div class="form-body">
				<ul class="nav nav-tabs final-login">
			        <li class="active"><a data-toggle="tab" href="#sectionA">Sign In</a></li>
			        <li><a data-toggle="tab" href="#sectionB">Join us!</a></li>
			    </ul>
			    <div class="tab-content">
    <div id="sectionA" class="tab-pane fade in active">
        <div class="innter-form">
            <form class="sa-innate-form" method="post" action="/">
            		{% csrf_token %}
		            <label>Username</label>
		            <input type="text" name="username" required>
		            <label>Password</label>
		            <input type="password" name="password" required>
		            <button type="submit">Sign In</button>
		            <!--<a href="">Forgot Password?</a>-->
            </form>
            </div>
            <!--
            <div class="social-login">
            <p>- - - - - - - - - - - - - Sign In With - - - - - - - - - - - - - </p>
    		<ul>
            <li><a href=""><i class="fa fa-facebook"></i> Facebook</a></li>
            <li><a href=""><i class="fa fa-google-plus"></i> Google+</a></li>
            <li><a href=""><i class="fa fa-twitter"></i> Twitter</a></li>
            </ul>
            </div>
        -->
            <div class="clearfix"></div>
        </div>
        <div id="sectionB" class="tab-pane fade">
			<div class="innter-form">
           <form class="sa-innate-form" method="post" action="/register/">
		            {% csrf_token %}
					{% include 'login/form_template.html' %}
		            <button type="submit">Join now</button>
		            <!--<a href="">Forgot Password?</a>-->
            </form>
            </div>
            <!--
            <div class="social-login">
            <p>- - - - - - - - - - - - - Register With - - - - - - - - - - - - - </p>
			<ul>
            <li><a href=""><i class="fa fa-facebook"></i> Facebook</a></li>
            <li><a href=""><i class="fa fa-google-plus"></i> Google+</a></li>
            <li><a href=""><i class="fa fa-twitter"></i> Twitter</a></li>
            </ul>
            </div>
        -->
        </div>
    </div>

			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/login/sidebar.html
<nav class="navbar navbar-inverse sidebar" role="navigation">
    <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Brand</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav" style="width: 100%;">
				
				<li id="home" class=""><a href="/home">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
				
				<!--<li ><a href="#">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>-->
				<!--<li ><a href="#">Messages<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-envelope"></span></a></li>-->
				
				<li id="tasks" class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Tasks <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-cog"></span></a>
					<ul class="dropdown-menu forAnimate" role="menu">
						{% for tasks in task_list %}
						
						<li><a href="/tasks/{{ tasks.pk }}">{{ tasks.list_title}}</a></li>
						<!--<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li class="divider"></li>
						<li><a href="#">Separated link</a></li>
						<li class="divider"></li>
						<li><a href="#">One more separated link</a></li>-->
					
						{% endfor %}
					</ul>
				</li>
				
				
				
			</ul>
		</div>
	</div>

	<div class="container-fluid">
		<a href="{% url 'logout' %}">
			<div class="row" style="margin: 0;text-align: center;background: white;">
				<h4>LOG OUT</h4>
			</div>
		</a>
	</div>
</nav>

<script>
	$( document ).ready(function() {
		var path = location.pathname.split('/')[1];
	    if( path == "home"){
	    	$('#home').addClass('active')
	    }else if(path == "tasks"){
	    	$('#tasks').addClass('open')
	    }
	});

</script>